.\"                                      Hey, EMACS: -*- nroff -*-
.\" dbusmm-introspect manual page
.\" Copyright (C) 2008 Enrique Garcia <kike+glkm@eldemonionegro.com>
.TH DBUS-INTROSPEC 1 "#SHORTDATE#"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dbusmm-introspect \- DBus C++ wrapper introspect program
.SH SYNOPSIS
.B dbusmm-introspect
.RI [--system] <object_path> [<destination>]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B dbusmm-introspect
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBdbusmm-introspect\fP is a program that...
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-system
Show system info.
.TP
.B object_path
Show object_path info.
.TP
.B destination
Show destination info.
.SH SEE ALSO
.BR dbusmm-xml2cpp (1)
.br
The programs are documented fully by
.IR "The Rise and Fall of a Fooish Bar" ,
available via the Info system.
.SH AUTHOR
dbusmm-introspect was written by <Paolo Durante>.
.PP
This manual page was written by Enrique Garcia <kike+glkm@eldemonionegro.com>,
for the Debian project (but may be used by others).
